module.exports = 
    ATTEMPTING_AUTHENTICATION: 'ATTEMPTING_AUTHENTICATION'
    AUTHENTICATION_ERRORED: 'AUTHENTICATION_ERRORED'
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED'
    AUTHENTICATION_SUCCEEDED: 'AUTHENTICATION_SUCCEEDED'